// AUTO-GENERATED by scripts/generate-markers.mjs — do not edit by hand.
// Per-venue-type marker chips (emoji on ambient background) in @1x/@2x/@3x
// density buckets, drawn natively via <Marker image> on Android.

import type { MarkerSize } from '@/stores/ui.store';

export type MarkerIconState = 'default' | 'selected' | 'active';

export const VENUE_MARKER_ICONS: Record<
  string,
  Record<MarkerSize, Record<MarkerIconState, number>>
> = {
  karaoke: {
    small: {
      default: require('../assets/markers/venue-karaoke-sm.png'),
      selected: require('../assets/markers/venue-karaoke-sm-selected.png'),
      active: require('../assets/markers/venue-karaoke-sm-active.png'),
    },
    medium: {
      default: require('../assets/markers/venue-karaoke-md.png'),
      selected: require('../assets/markers/venue-karaoke-md-selected.png'),
      active: require('../assets/markers/venue-karaoke-md-active.png'),
    },
    large: {
      default: require('../assets/markers/venue-karaoke-lg.png'),
      selected: require('../assets/markers/venue-karaoke-lg-selected.png'),
      active: require('../assets/markers/venue-karaoke-lg-active.png'),
    },
  },
  nightclub: {
    small: {
      default: require('../assets/markers/venue-nightclub-sm.png'),
      selected: require('../assets/markers/venue-nightclub-sm-selected.png'),
      active: require('../assets/markers/venue-nightclub-sm-active.png'),
    },
    medium: {
      default: require('../assets/markers/venue-nightclub-md.png'),
      selected: require('../assets/markers/venue-nightclub-md-selected.png'),
      active: require('../assets/markers/venue-nightclub-md-active.png'),
    },
    large: {
      default: require('../assets/markers/venue-nightclub-lg.png'),
      selected: require('../assets/markers/venue-nightclub-lg-selected.png'),
      active: require('../assets/markers/venue-nightclub-lg-active.png'),
    },
  },
  sports_bar: {
    small: {
      default: require('../assets/markers/venue-sports_bar-sm.png'),
      selected: require('../assets/markers/venue-sports_bar-sm-selected.png'),
      active: require('../assets/markers/venue-sports_bar-sm-active.png'),
    },
    medium: {
      default: require('../assets/markers/venue-sports_bar-md.png'),
      selected: require('../assets/markers/venue-sports_bar-md-selected.png'),
      active: require('../assets/markers/venue-sports_bar-md-active.png'),
    },
    large: {
      default: require('../assets/markers/venue-sports_bar-lg.png'),
      selected: require('../assets/markers/venue-sports_bar-lg-selected.png'),
      active: require('../assets/markers/venue-sports_bar-lg-active.png'),
    },
  },
  bowling: {
    small: {
      default: require('../assets/markers/venue-bowling-sm.png'),
      selected: require('../assets/markers/venue-bowling-sm-selected.png'),
      active: require('../assets/markers/venue-bowling-sm-active.png'),
    },
    medium: {
      default: require('../assets/markers/venue-bowling-md.png'),
      selected: require('../assets/markers/venue-bowling-md-selected.png'),
      active: require('../assets/markers/venue-bowling-md-active.png'),
    },
    large: {
      default: require('../assets/markers/venue-bowling-lg.png'),
      selected: require('../assets/markers/venue-bowling-lg-selected.png'),
      active: require('../assets/markers/venue-bowling-lg-active.png'),
    },
  },
  billiards: {
    small: {
      default: require('../assets/markers/venue-billiards-sm.png'),
      selected: require('../assets/markers/venue-billiards-sm-selected.png'),
      active: require('../assets/markers/venue-billiards-sm-active.png'),
    },
    medium: {
      default: require('../assets/markers/venue-billiards-md.png'),
      selected: require('../assets/markers/venue-billiards-md-selected.png'),
      active: require('../assets/markers/venue-billiards-md-active.png'),
    },
    large: {
      default: require('../assets/markers/venue-billiards-lg.png'),
      selected: require('../assets/markers/venue-billiards-lg-selected.png'),
      active: require('../assets/markers/venue-billiards-lg-active.png'),
    },
  },
  hookah: {
    small: {
      default: require('../assets/markers/venue-hookah-sm.png'),
      selected: require('../assets/markers/venue-hookah-sm-selected.png'),
      active: require('../assets/markers/venue-hookah-sm-active.png'),
    },
    medium: {
      default: require('../assets/markers/venue-hookah-md.png'),
      selected: require('../assets/markers/venue-hookah-md-selected.png'),
      active: require('../assets/markers/venue-hookah-md-active.png'),
    },
    large: {
      default: require('../assets/markers/venue-hookah-lg.png'),
      selected: require('../assets/markers/venue-hookah-lg-selected.png'),
      active: require('../assets/markers/venue-hookah-lg-active.png'),
    },
  },
  board_games: {
    small: {
      default: require('../assets/markers/venue-board_games-sm.png'),
      selected: require('../assets/markers/venue-board_games-sm-selected.png'),
      active: require('../assets/markers/venue-board_games-sm-active.png'),
    },
    medium: {
      default: require('../assets/markers/venue-board_games-md.png'),
      selected: require('../assets/markers/venue-board_games-md-selected.png'),
      active: require('../assets/markers/venue-board_games-md-active.png'),
    },
    large: {
      default: require('../assets/markers/venue-board_games-lg.png'),
      selected: require('../assets/markers/venue-board_games-lg-selected.png'),
      active: require('../assets/markers/venue-board_games-lg-active.png'),
    },
  },
  arcade: {
    small: {
      default: require('../assets/markers/venue-arcade-sm.png'),
      selected: require('../assets/markers/venue-arcade-sm-selected.png'),
      active: require('../assets/markers/venue-arcade-sm-active.png'),
    },
    medium: {
      default: require('../assets/markers/venue-arcade-md.png'),
      selected: require('../assets/markers/venue-arcade-md-selected.png'),
      active: require('../assets/markers/venue-arcade-md-active.png'),
    },
    large: {
      default: require('../assets/markers/venue-arcade-lg.png'),
      selected: require('../assets/markers/venue-arcade-lg-selected.png'),
      active: require('../assets/markers/venue-arcade-lg-active.png'),
    },
  },
  standup: {
    small: {
      default: require('../assets/markers/venue-standup-sm.png'),
      selected: require('../assets/markers/venue-standup-sm-selected.png'),
      active: require('../assets/markers/venue-standup-sm-active.png'),
    },
    medium: {
      default: require('../assets/markers/venue-standup-md.png'),
      selected: require('../assets/markers/venue-standup-md-selected.png'),
      active: require('../assets/markers/venue-standup-md-active.png'),
    },
    large: {
      default: require('../assets/markers/venue-standup-lg.png'),
      selected: require('../assets/markers/venue-standup-lg-selected.png'),
      active: require('../assets/markers/venue-standup-lg-active.png'),
    },
  },
  live_music: {
    small: {
      default: require('../assets/markers/venue-live_music-sm.png'),
      selected: require('../assets/markers/venue-live_music-sm-selected.png'),
      active: require('../assets/markers/venue-live_music-sm-active.png'),
    },
    medium: {
      default: require('../assets/markers/venue-live_music-md.png'),
      selected: require('../assets/markers/venue-live_music-md-selected.png'),
      active: require('../assets/markers/venue-live_music-md-active.png'),
    },
    large: {
      default: require('../assets/markers/venue-live_music-lg.png'),
      selected: require('../assets/markers/venue-live_music-lg-selected.png'),
      active: require('../assets/markers/venue-live_music-lg-active.png'),
    },
  },
  other: {
    small: {
      default: require('../assets/markers/venue-other-sm.png'),
      selected: require('../assets/markers/venue-other-sm-selected.png'),
      active: require('../assets/markers/venue-other-sm-active.png'),
    },
    medium: {
      default: require('../assets/markers/venue-other-md.png'),
      selected: require('../assets/markers/venue-other-md-selected.png'),
      active: require('../assets/markers/venue-other-md-active.png'),
    },
    large: {
      default: require('../assets/markers/venue-other-lg.png'),
      selected: require('../assets/markers/venue-other-lg-selected.png'),
      active: require('../assets/markers/venue-other-lg-active.png'),
    },
  },
};

// Pre-rendered cluster badges (Android cannot snapshot dynamic <View>
// markers reliably). Buckets: exact 2–9, then 10+/20+/50+/99+.
export const CLUSTER_ICONS: Record<string, number> = {
  '2': require('../assets/markers/cluster-2.png'),
  '3': require('../assets/markers/cluster-3.png'),
  '4': require('../assets/markers/cluster-4.png'),
  '5': require('../assets/markers/cluster-5.png'),
  '6': require('../assets/markers/cluster-6.png'),
  '7': require('../assets/markers/cluster-7.png'),
  '8': require('../assets/markers/cluster-8.png'),
  '9': require('../assets/markers/cluster-9.png'),
  '10+': require('../assets/markers/cluster-10plus.png'),
  '20+': require('../assets/markers/cluster-20plus.png'),
  '50+': require('../assets/markers/cluster-50plus.png'),
  '99+': require('../assets/markers/cluster-99plus.png'),
};

/** Map a live cluster count onto one of the pre-rendered label buckets. */
export function clusterCountLabel(count: number): string {
  if (count <= 9) return String(count);
  if (count < 20) return '10+';
  if (count < 50) return '20+';
  if (count < 99) return '50+';
  return '99+';
}
